version: '3.9'
services:
  api-rest-evaluador-aed:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 3000:3000
    volumes:
      - ./:/app
      #- /app/node_modules
    restart: always
    env_file:
        - .env
    dns:
      8.8.8.8